### ISSUE TITLE
How to fetch the paper

### ISSUE THREAD

**Issue by dongqiaqia** [Vegeta2020/SE-SSD#1]

**Comment by Son-Goku-gpu** [comment]
Hi @dongqiaqia , we have submitted a related funding proposal months ago, and my supervisor suggested me to release the paper after the proposal decisions are annouced. So, please wait until Middle April.

**Comment by Vegeta2020** [comment]
Hi @dongqiaqia , we have submitted a related funding proposal months ago, and my supervisor suggested me to release the paper after the proposal decisions are annouced. So, please wait until Middle April.
