### ISSUE TITLE
 CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by vivi0604** [Vegeta2020/SE-SSD#10]
I'm really appreciate you for the nice source code, I run test.py and encountered the following problem：
![image](https://user-images.githubusercontent.com/38038575/125777534-2dd4cafc-7e75-457b-add8-9905eae2aefd.png)
Can you give me some tips to make it work?

**Comment by Vegeta2020** [comment]
It seems your env setting issue, and you may set trigger points in line 922 and 1032 to check more.

**Comment by weiyangdaren** [comment]
I encountered the same problem，have you solved it ？
