### ISSUE TITLE
Problem during training from scratch

### ISSUE THREAD

**Issue by wei-tim** [Vegeta2020/SE-SSD#13]
Hey,
thanks for sharing the interesting project. 

When I tried training from scratch without CIA-SSD pre-trained model, I found during computing consistency loss, the valid number of student and teacher is too large, even if the score threshold is given (0.3 in the code).  So the iou computation between "top_box_preds_stu" and "top_box_preds_tea" will cause "cuda out of memory" error... 

Many thanks in advance

Best regards,
Tim

**Comment by wei-tim** [comment]
![image](https://user-images.githubusercontent.com/53610385/126134668-5be95fa6-acc0-4e94-a1b8-b731f4dd0e4c.png)
The problem happens in this line within "consistency_loss" function in the "mg_head_sessd.py"

**Comment by wei-tim** [comment]
If I understand correctly, a pre-trained CIA-SSD model is necessary? 
Could you pls also share this CIA-SSD model?

Thx in advance :-)

**Comment by Vegeta2020** [comment]
Yes, try to use a pre-trained model.

**Comment by wei-tim** [comment]
@Vegeta2020 
Hi, 
thx for the reply. Could you please share the pre-trained CIA-SSD model?

**Comment by Vegeta2020** [comment]
> @Vegeta2020
> Hi,
> thx for the reply. Could you please share the pre-trained CIA-SSD model?

I guess it may be downloaded from CIA-SSD codebase.
