### ISSUE TITLE
command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by vivi0604** [Vegeta2020/SE-SSD#15]
When i run  python setup.py install and encountered the following problem：
![image](https://user-images.githubusercontent.com/38038575/126293200-e513f4c1-1fb9-42e3-bff5-0ae82d4d6d89.png)
![image](https://user-images.githubusercontent.com/38038575/126293311-893a4382-2eca-4083-abe2-21a2dc421207.png)
Can you give me some tips to make it work?

**Comment by colian** [comment]
hello, can you share how to solve it? @vivi0604

**Comment by hughjazzman** [comment]
@colian This is because `AT_CHECK` is deprecated in favour of `TORCH_CHECK` in PyTorch 1.5+. [See here for solution to add the following code to affected files.](https://github.com/mrlooi/rotated_maskrcnn/issues/31#issuecomment-631416601)
```C++
#ifndef AT_CHECK
#define AT_CHECK TORCH_CHECK 
#endif
```

**Comment by colian** [comment]
@hughjazzman thanks for help, i will try.
