### ISSUE TITLE
iou3d build problem

### ISSUE THREAD

**Issue by SH-Tan** [Vegeta2020/SE-SSD#22]
Hello, when I want to build the iou3d,

I meet the following errors:

g++: error: /data/stan/SE-SSD/SE-SSD/det3d/core/iou3d/build/temp.linux-x86_64-3.6/src/iou3d.o: 没有那个文件或目录
g++: error: /data/stan/SE-SSD/SE-SSD/det3d/core/iou3d/build/temp.linux-x86_64-3.6/src/iou3d_kernel.o: 没有那个文件或目录
g++: error: /data/stan/SE-SSD/SE-SSD/det3d/core/iou3d/build/temp.linux-x86_64-3.6/src/iou3d_cpu.o: 没有那个文件或目录

where can I find these files?

**Comment by SH-Tan** [comment]
I run these two lines:

cd ./SE-SSD/det3d/core/iou3d
$ python setup.py install

**Comment by Vegeta2020** [comment]
The "build" directory should be created due to the running of the commands. If they have existed, how about deleting them and re-running these  commands?

**Comment by SH-Tan** [comment]
I downloaded the Det3D code and built it. Then I find these files in that package. I don't know if I prepared the environment in a wrong way? Maybe I shouldn't build the Det3d package at first.

**Comment by Vegeta2020** [comment]
There may exist some conflicts. But you could use "mv Det3D Det3D-backup" to change the name of your built Det3D, then you should install our SE-SSD.

**Comment by stidk** [comment]
I encountered the same problem. Have you solved it.

**Comment by stidk** [comment]
File "/home/dk/anaconda3/envs/se-ssd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 539, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/dk/anaconda3/envs/se-ssd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1360, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/dk/anaconda3/envs/se-ssd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
-------------------------------------------------------------------------------------------------------------------------------
I also encountered such a problem, may be i should change pytorch edition?

**Comment by SH-Tan** [comment]
> ## File "/home/dk/anaconda3/envs/se-ssd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 539, in unix_wrap_ninja_compile
> with_cuda=with_cuda)
> File "/home/dk/anaconda3/envs/se-ssd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1360, in _write_ninja_file_and_compile_objects
> error_prefix='Error compiling objects for extension')
> File "/home/dk/anaconda3/envs/se-ssd/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
> raise RuntimeError(message) from e
> RuntimeError: Error compiling objects for extension
> 
> I also encountered such a problem, may be i should change pytorch edition?

I copy the missing files from the Det3d I built separately, then I can build the code. I use the python 3.6 and pytorch 1.6

**Comment by stidk** [comment]
After run Det3d, 'iou3d_cpu.o' file was not generated.

**Comment by SH-Tan** [comment]
> After run Det3d, 'iou3d_cpu.o' file was not generated.

I copy the related files from this code to generate 'iou3d_cpu.o' in Det3d, you also need to revise the 'setup.py'. You always can find missing files in either this code or the Det3d package.

**Comment by SH-Tan** [comment]
I found the real problem is the version of the pytorch. I used 1.6 before, when I changed the version to 1.4, it can build successfully.

**Comment by Ebraheem1** [comment]
I have a question regarding Det3d, why do we need to build it? All the files in this repo are inside the directory of det3d in SE-SSD. Thus, if the aim is to work with SE-SSD, then it would not help to install Det3d right?

**Comment by Vegeta2020** [comment]
There is no need to install Det3D, and it may call the files in the Det3D when running SE-SSD. As the guy mentioned, the pytorch version may also affect the installation.
