### ISSUE TITLE
What is the pre-trained model?

### ISSUE THREAD

**Issue by s-ryosky** [Vegeta2020/SE-SSD#24]
I have run train.py and then the following error has occurred.
```
OSError: /mnt/proj50/zhengwu/saved_model/KITTI/proj52/megvii/second/pre_trained_model_2/epoch_60.pth is not a checkpoint file
```

What is the pre-trained mode?
Does the self-training on SE-SSD use a pre-trained model as the initial values of teacher model?
If yes, how can I get or create the pre-trained model?

**Comment by Vegeta2020** [comment]
You may train a single SSD or use the pre-trained CIA-SSD, which could be downloaded in CIA-SSD repostiory.

**Comment by s-ryosky** [comment]
Thank you for your reply.
I will try it.

**Comment by hanswang1** [comment]
> Yes, we use a pre-trained model to initialize both student and teacher model. You may train a single SSD or use the pre-trained CIA-SSD, which could be downloaded in CIA-SSD repostiory.

Where is epoch_60.pth in CIA-SSD repository?
