### ISSUE TITLE
【spconv】OSError: /root/anaconda3/envs/Det3D/lib/python3.6/site-packages/spconv/libspconv.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtESt10shared_ptrIS0_EPSo

### ISSUE THREAD

**Issue by HuangCongQing** [Vegeta2020/SE-SSD#25]
请问，是不是和spconv1.0不兼容啊？

![image](https://user-images.githubusercontent.com/20675770/128833870-c18bdc10-4f55-45a3-b10b-d2d6bfd6a519.png)

**Comment by Vegeta2020** [comment]
是可以兼容的。你这个看上去像是spconv没有装好。

**Comment by LuYujing-97** [comment]
> 请问，是不是和spconv1.0不兼容啊？
> 
> ![image](https://user-images.githubusercontent.com/20675770/128833870-c18bdc10-4f55-45a3-b10b-d2d6bfd6a519.png)
您好 ，请问您这个问题最后是怎么解决的呢，我现在也遇到了同样的问题
