### ISSUE TITLE
export pytorch model to onnx model and deploy model in tensorrt environment?

### ISSUE THREAD

**Issue by ghost** [Vegeta2020/SE-SSD#26]
Thanks for your work and project, I have trained a model with your method. 

I want to deploy this model with tensorrt inference engine in embedded platform, the first thing to do is export pytorch model to onnx model, but there are many dictionary data structures and custom layers/operators in this project, how to modify input、output and network ? 

Could you give me some ideas ? Thanks !

**Comment by Vegeta2020** [comment]
You may modify input in pipelines, and modify output in mg_head_sessd.py, and re-format the input and output as you like.
