### ISSUE TITLE
Trained model of SE-SSD

### ISSUE THREAD

**Issue by WWW2323** [Vegeta2020/SE-SSD#27]
Hi~, your work is very awesome. But when I use the trained model you provide (https://drive.google.com/file/d/1M2nP_bGpOy0Eo90xWFoTIUkjhdw30Pjs/view?usp=sharing) to evaluate val set (by running "python test.py"), I get the results as follow:
Evaluation official_AP_11: car AP(Average Precision)@0.70, 0.70, 0.70:
bbox AP:90.61, 89.47, 89.02
bev  AP:89.94, 88.11, 87.44
3d   AP:88.44, 79.07, 78.27
aos  AP:90.51, 89.10, 88.46
Evaluation official_AP_40: car AP(Average Precision)@0.70, 0.70, 0.70:
bbox AP:96.27, 93.00, 90.56
bev  AP:93.25, 89.64, 87.23
3d   AP:89.73, 83.08, 80.57
aos  AP:96.12, 92.55, 89.97

Is the trained model a checkpoint of CIA-SSD or SE-SSD? The results of SE-SSD you provide is as follow:
AP_11: car AP(Average Precision)@0.70, 0.70, 0.70:
bbox AP:98.72, 90.10, 89.57
bev  AP:90.61, 88.76, 88.18
3d   AP:90.21, 86.25, 79.22
aos  AP:98.67, 89.86, 89.16
AP_40: car AP(Average Precision)@0.70, 0.70, 0.70:
bbox AP:99.57, 95.58, 93.16
bev  AP:96.70, 92.15, 89.74
3d   AP:93.75, 86.18, 83.50
aos  AP:99.52, 95.28, 92.69

Can you provide a checkpoint of the above results?  I can’t train SE-SSD because of many environmental issues. Thanks very much!

**Comment by shxzhao** [comment]
Can you provide the model by baidu drive for me, I cant use the google drive. Thanks!@WWW2323

**Comment by WWW2323** [comment]
I have no baidu drive, you can give me your email if you need model. @shxzhao

**Comment by shxzhao** [comment]
985525622@qq.com  Thanks!@WWW2323

**Comment by pigtigger** [comment]
I am not sure if I train the model in a right way. I want to use se-ssd model in my work but the result trained by myself  is not good as expected, can you provide a checkpoint of the results mentioned by @WWW2323 ? Thanks!
![image](https://user-images.githubusercontent.com/39974202/129482794-acf44b57-d2e2-453b-a557-655bd96b3018.png)

**Comment by WWW2323** [comment]
Try this [link](https://drive.google.com/file/d/1M2nP_bGpOy0Eo90xWFoTIUkjhdw30Pjs/view?usp=sharing) if you can get google drive, or give me your email, and i seed you the model.

**Comment by pigtigger** [comment]
Thanks！
is the model in google drive the final one trained by se ssd framework or the initial model for teacher and student model？




------------------ Original ------------------
From: WWW2323 ***@***.***&gt;
Date: Sun,Aug 15,2021 11:57 PM
To: Vegeta2020/SE-SSD ***@***.***&gt;
Cc: lihe ding ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [Vegeta2020/SE-SSD] Trained model of SE-SSD (#27)





 
Try this link if you can get google drive, or give me your email, and i seed you the model.

**Comment by WWW2323** [comment]
The model is provided by author in README.md. It is the initial model, not the final model.

**Comment by pigtigger** [comment]
Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vegeta2020/SE-SSD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 凌晨0:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vegeta2020/SE-SSD] Trained model of SE-SSD (#27)





 
The model is provided by author in README.md. It is the initial model, not the final model.
