### ISSUE TITLE
How to save the eval result

### ISSUE THREAD

**Issue by shxzhao** [Vegeta2020/SE-SSD#28]
I want to get the txt for predicted result. I am looking forward to your reply!

**Comment by sunwonHong** [comment]
You can save the results from test.py

Use this part on test.py

if args.txt_result:  # True
            res_dir = os.path.join(cfg.work_dir, "predictions")
            os.makedirs(res_dir, exist_ok=True)
            for dt in detections:
                with open(os.path.join(res_dir, "%06d.txt" % int(dt["metadata"]["token"])), "w") as fout:
                    lines = kitti.annos_to_kitti_label(dt)
                    for line in lines:
                        fout.write(line + "\n")

It would have been annotated first.

**Comment by shxzhao** [comment]
Thanks for your reply! It works
