### ISSUE TITLE
Training setting..

### ISSUE THREAD

**Issue by adolys66** [Vegeta2020/SE-SSD#29]
Hi,
I have a question about training details.
I trained SE-SSD several times, but the performance is different from your paper.

In AP_40 with (0.7, 0.7, 0.7), 3d detection AP for easy, moderate, and hard sets are respectively about 93.XX, 84.XX, and 81.XX. with the CIA-SSD model provided in https://github.com/Vegeta2020/CIA-SSD, your default configuration (examples/second/configs/config.py), and the provided codes.
This AP seems similar to the performance of only consistency loss mode in table 3.

Cons loss ODIoU SA-DA Easy Moderate Hard
       -            -           -     92.58 83.22 80.15
       -            -           X     93.02 83.70 80.68
       -            X           -     93.07 83.85 80.78
       X            -           -     **93.13 84.15 81.17**
       X            X          -     93.17 85.81 83.01
       X            X          X     93.19 86.12 83.31

Please let me know if there are any missing details.

**Comment by AndyYuan96** [comment]
> Hi,
> I have a question about training details.
> I trained SE-SSD several times, but the performance is different from your paper.
> 
> In AP_40 with (0.7, 0.7, 0.7), 3d detection AP for easy, moderate, and hard sets are respectively about 93.XX, 84.XX, and 81.XX. with the CIA-SSD model provided in https://github.com/Vegeta2020/CIA-SSD, your default configuration (examples/second/configs/config.py), and the provided codes.
> This AP seems similar to the performance of only consistency loss mode in table 3.
> 
> Cons loss ODIoU SA-DA Easy Moderate Hard
> - - - 92.58 83.22 80.15
> - - X 93.02 83.70 80.68
> - X - 93.07 83.85 80.78
> X - - **93.13 84.15 81.17**
> X X - 93.17 85.81 83.01
> X X X 93.19 86.12 83.31
> 
> Please let me know if there are any missing details.

same result with you, no improvement.
