### ISSUE TITLE
Questions about paper

### ISSUE THREAD

**Issue by tianweiy** [Vegeta2020/SE-SSD#3]
Really Nice Work! I get two quick questions.

1> is the scale-aware data augmentation also used for preprocessing inputs for both teacher/student networks? 

2> If the answer for 1 is no, for the last two rows of table 3, what does removing SA-DA mean? Does it mean that you remove SA-DA for the student network's input? And now the student network's prediction is based on a global transformed point cloud (but not dropout / sparsified through SA-DA)? It is surprising that this still works quite well.  

Thanks

**Comment by Vegeta2020** [comment]
Hi @tianweiy , glad to hear your questions:
1> no, SA-DA is only for student network to enlarge the sample diversity;
2> yes, it means removing SA-DA for the student. Indeed, global augmentation already leads to a large improvement.

**Comment by tianweiy** [comment]
cool, thanks!
