### ISSUE TITLE
How to modify the voxel's size(range)

### ISSUE THREAD

**Issue by sunwonHong** [Vegeta2020/SE-SSD#30]
I succeed in training and testing with Kittidataset.
It works well. Thank you!

By the way, i have my custom dataset(Format is same with Kittidataset)
so i want to change the voxel generator range on config.py
I changed like this
range=[0, -40.0, -3.0, 70.4, 40.0, 1.0], -> range=[-52.8, -32.0, -3.0, 52.8, 32.0, 1.0],

But i got this error
RuntimeError: The size of tensor a (84480) must match the size of tensor b (70400) at non-singleton dimension 0
I know this error is caused by incorrect the number of voxel from the different range.
Is there any ways to train and test with like my different range without changing existing model architecture?
What should i change?

**Comment by Vegeta2020** [comment]
The feature map size will also be changed, so you need to check the network details and data preprocess carefully to comply with your new range.

**Comment by sunwonHong** [comment]
@Vegeta2020 

Did you test with only Kitti Dataset or Have you tested with others like Nuscense, Lift?

**Comment by Vegeta2020** [comment]
I test it only on kitti.
