### ISSUE TITLE
original_pp_mghead_syncbn_kitti.py(Point_Pillars)

### ISSUE THREAD

**Issue by sunwonHong** [Vegeta2020/SE-SSD#31]
original_pp_mghead_syncbn_kitti.py is for pointpillars Net, right?

To use pointpillars, all i have to do is change this on train.py?
before : parser.add_argument("--config", default='../examples/second/configs/config.py', help="train config file path")
after : parser.add_argument("--config", default='../examples/point_pillars/configs/original_pp_mghead_syncbn_kitti.py', help="train config file path")

I think additional process must be needed.
Could you let know me how i can use pointpillars? What should i change?

**Comment by Vegeta2020** [comment]
I haven't do training with pointpillars, this file is just saved as in Det3D. I guess you need to check the pointpillar network details to be consistent with the input and output data processing.

**Comment by sunwonHong** [comment]
OK. Thank you for replying!
