### ISSUE TITLE
Protobuf problem during installation

### ISSUE THREAD

**Issue by fate55** [Vegeta2020/SE-SSD#38]
When I run `python setup.py build develop` I get the following output:

`Installed /home/user/Dokumente/SSDs/SE-SSD`
`Processing dependencies for det3d==1.0rc0+b68068d`
`error: protobuf 3.6.1 is installed but protobuf>=3.8.0 is required by {'tensorboardX'}`

I think protobuf was installed with ros. How can I solve this problem? I already tried to upgrade it: 

with `pip show protobuf` I get

```
Name: protobuf
Version: 3.17.3
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /home/fatih/.local/lib/python3.8/site-packages
Requires: six
Required-by: tensorboardX, det3d
```

**Comment by Vegeta2020** [comment]
Hi, @fate55 You may try to install tensorboardX first.
