### ISSUE TITLE
Without any weight files(load files)

### ISSUE THREAD

**Issue by sunwonHong** [Vegeta2020/SE-SSD#39]
I want to train without any weight files(load files).
But in order to train that, many cuda memories are needed(over 18 GiB).
I read that you have used a single TITAN Xp GPU, but i think it doesn't work on over 18 GiB things.
Did you initially train the model in parallel GPU or by using another GPU(like RTX 3090)?

and if i have enough CUDA memories, can i train the model normally?

Your response will be very helpful. Thank you.

**Comment by Vegeta2020** [comment]
@sunwonHong One solution is to train a SSD for several iteration, and then load it to our SE-SSD and continue the next training. By this way, it can utilize the slightly converaged model to avoid the initial predictions to be invalid values, e.g., randomly negative values for IoU calculation.  Then, the consumed memory will be very limited and one GPU will be enough.
