### ISSUE TITLE
soft targets

### ISSUE THREAD

**Issue by monster-ghost** [Vegeta2020/SE-SSD#4]
I would like to know how to understand 

“soft targets from the teacher often have higher entropy, thus offering
more information [9] for the student to learn from”

In a classified task, I can understand that. Because hard target is a one hot vector, but soft is not, so it will provide more information. 
But how can I understand the soft target in the detection task has more information?

**Comment by crawfish3** [comment]
If we denote the box location with "[" & "]", and denote the target with "|" & "|", then 
soft target could be   [|...............  |    ]
hard target is             [|...............      |]
By comparison, we may know that the soft target is more consistent with the ground-truth point cloud patterns especially in the occlussion cases, thus realizes better model convergence.

**Comment by Vegeta2020** [comment]
If we denote the box location with "[" & "]", and denote the target with "|" & "|", then
`soft target is [|---------____|___]`
`hard target is [|---------_______|]`
in which, "-" and "_" mean point and empty space, respectively.
By comparison, we may know that the soft target is more consistent with the ground-truth point cloud patterns especially in the occlussion cases, thus realizes better model convergence.

**Comment by a1anzvvy** [comment]
Could you explain more why soft target have a more consistent pattern with the ground-truth point cloud patterns? Isn't the teacher's model also trained from hard targets in the pre-trained model?
