### ISSUE TITLE
How was the pretrained weight(load file) made?

### ISSUE THREAD

**Issue by sunwonHong** [Vegeta2020/SE-SSD#41]
I would like to know how the pretrained weight(load file) was made.

Is it made by using Kitti dataset simply or did you use other datasets or processes for initialization?

How did you make it?

The reason why i asking this is that i want to train without any weights initially.

Thank you.

**Comment by Vegeta2020** [comment]
@sunwonHong It is trained with a single CIA-SSD, you may find it in our AAAI 2021 repostiory.
