### ISSUE TITLE
How to train SE-SSD on 3-classes data simultaneously?

### ISSUE THREAD

**Issue by Typolo** [Vegeta2020/SE-SSD#44]
Thank you for your released code.
I try to train model on 3-classes with provided pre-trained model, but there is an error " loaded state dict contains a parameter group that doesn't match the size of optimizer's group";
Without the pre-trained model, the error(runtimeError: CUDA out of memory. Tried to allocate 18.19 GiB (GPU 0; 10.76 GiB total capacity; 2.85 GiB already allocated; 1.96 GiB free; 296.54 MiB cached)) happend.
How can i solve the problem? Looking forward to your reply!

**Comment by Vegeta2020** [comment]
See the issue https://github.com/Vegeta2020/SE-SSD/issues/23
