### ISSUE TITLE
a question about ODIoU loss

### ISSUE THREAD

**Issue by ozzCb** [Vegeta2020/SE-SSD#5]
Great works! I got a question when reading paper:
how do you calculate IoU between Bp and Bg in ODIoU loss? Do you calculate axis-aligned IoU or rotated IoU (the backward seems complicated)?

**Comment by Vegeta2020** [comment]
Indeed, it's complex due to the gradient back-propagation, and IoU are calculated as non-axis-aligned. The code will be released in a few weeks and reveal all details.
