### ISSUE TITLE
cudaerror:an illeage memary was account

### ISSUE THREAD

**Issue by wangyanglang** [Vegeta2020/SE-SSD#53]
SE-SSD-master\det3d\models\bbox_heads\mg_head_sessd.py   ans_iou = ans_iou[mask1],cudaerror:an illeage memary was account
hello, when i run this code ,batch-size=1,GPU:tesla100,32G,when run train.py ,it failed with this error,can you give me some helps?

**Comment by Vegeta2020** [comment]
See this issue https://github.com/Vegeta2020/SE-SSD/issues/47
