### ISSUE TITLE
Consistency Loss doesn't match paper

### ISSUE THREAD

**Issue by sdelcore** [Vegeta2020/SE-SSD#54]
Hi, thank you for the great work!

Your paper identifies two components to your consistency loss (classification and IOU) however your code uses 3 components (box, classification, and IOU). Is there a reason for this?

https://github.com/Vegeta2020/SE-SSD/blob/2dd4b4fe7672fd431b25d29956339a7e7ead0c96/det3d/models/bbox_heads/mg_head_sessd.py#L702

Also, for the IOU loss, you add 1 then divide the values by 2. Why is this performed?
https://github.com/Vegeta2020/SE-SSD/blob/2dd4b4fe7672fd431b25d29956339a7e7ead0c96/det3d/models/bbox_heads/mg_head_sessd.py#L690-L691

**Comment by wangyanglang** [comment]
hi,i got some trouble,Has it happened to you before ? i sincerely hope to receive  your reply,thank you very much 
SE-SSD/det3d/models/bbox_heads/mg_head_sessd.py     
Line583
583 ans_iou = ans_iou[mask1]
when i run train.py,it failed with this error:
RuntimeError: copy_if failed to synchronize: cudaErrorIllegaAddres:an illegal memory access was encountered


pytorch: 3.6.8, pytorch:1.3,cuda:10.1 ,GPU:tesla  32G
