### ISSUE TITLE
promble in training

### ISSUE THREAD

**Issue by 18456432930** [Vegeta2020/SE-SSD#55]
I execute code 'python ./SE-SSD/tools/create_data.py' then get the wrong  'FileNotFoundError: [Errno 2] No such file or directory: '/data/zhengwu/KITTI/object/kitti_infos_train.pkl'' 
I want to know how to get the file 'kitti_infos_train.pkl'

**Comment by ferrari700** [comment]
Has your problem been solved? I also encountered the same problem, thank you！

**Comment by 18456432930** [comment]
sorry，I don't to slove the promble.

**Comment by Vegeta2020** [comment]
@ferrari700 @18456432930 Please find the solution in https://github.com/poodarchu/Det3D/blob/master/GETTING_STARTED.md. It's about executing the create_data.py
