### ISSUE TITLE
How to bulid it.

### ISSUE THREAD

**Issue by stidk** [Vegeta2020/SE-SSD#58]
I have tried many versions of python(3.6.5,3.6.10),pytorch(1.4.0,1.1.0,1.6.0,1.7.0),cuda(10.0,10.1,10.2),it does not work.Because of spconv,det3d and ‘python ./SE-SSD/tools/create_data.py’,i want to know what are you version of python,pytorch,cuda,cudnn.I have bulit it for a week.Please,who can help me.

**Comment by kangzixiang** [comment]
Did you succeed？
I successfully deployed det3D， but the spconv is still fail.
i want build it on windows, and i use pytorch 1.10, cuda 11.4, python 3.7.

**Comment by kangzixiang** [comment]
the det3D need modify some code for adaptation Windows.
