### ISSUE TITLE
How to install iou3d in windows10

### ISSUE THREAD

**Issue by leeh8911** [Vegeta2020/SE-SSD#62]
I have some problem.

When I follow your guide in readme, I stucked in installing iou3d.

I met below error massege
"error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2"

My environment: Windows10, python3.6, torch1.10.0+cu102, cuda10.2

**Comment by kangzixiang** [comment]
Did you succeed？
the det3D need modify some code for adaptation Windows.
I successfully deployed det3D and iou3d， but the spconv is still fail.
i want build it on windows, and i use pytorch 1.10, cuda 11.4, python 3.7.
