### ISSUE TITLE
How to extend the effective detection range

### ISSUE THREAD

**Issue by Jason-wwww** [Vegeta2020/SE-SSD#65]
In order to extend the effective detection range, I modify the value of "target_assigner", "test_config" and "voxel_generator" in the config file.

`anchor_ranges=[0, -40.0, -1.0, 70.4, 40.0, 1.0]` ->`anchor_ranges=[0, -40.0, -1.0, 102.4, 40.0, 1.0]` in "target_assigner"

`range=[0, -40.0, -3.0, 70.4, 40.0, 1.0]` -> `anchor_ranges=[0, -40.0, -3.0, 102.4, 40.0, 1.0]` in "voxel_generator" 

`post_center_limit_range=[0, -40.0, -5.0, 70.4, 40.0, 5.0]` -> `anchor_ranges=[0, -40.0, -5.0, 102.4, 40.0, 5.0]` in "test_config"

However, the effective detection range is also about 70m. What can I do to extend the effective detection range?

**Comment by Vegeta2020** [comment]
@Jason-wwww Do you test it on KITTI or a new dataset? If on KITTI, there may exist very few points out of 70m range. If on a new dataset, I wonder if there exist enough points for the long-distance objects. For your revisions, I think they are right, while I'm not sure if they are enough as I don't remember too much, but I suggest you to check more on the results before NMS -> then the confidence maps of the detection head, by this way, you should find out how to address it.
