### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by awethaileslassie** [Vegeta2020/SE-SSD#66]
Hi @Vegeta2020 

Thank you for the great work.

Can you please include a custom dataset data loader with only point clouds and 3D bounding box (i.e Argoverse/ Waymo)?

**Comment by Vegeta2020** [comment]
The code is mainly in preprocess.py and I simplify the code for other datasets, but you main find it in the repository Det3D that provides preprocess code for all datadets.
