### ISSUE TITLE
some confusion about data augmentation QAQ

### ISSUE THREAD

**Issue by OuyangJunyuan** [Vegeta2020/SE-SSD#70]
different catagories object, like 'Car' and 'Pedestrain' , part points cloud will be swapped ?

**Comment by Vegeta2020** [comment]
The code was wrritten for a single class, as we trained SE-SSD on each class separately for better performance. If you want to train it on all classes, you may use the gt_names to separate different classes and perform swap on each class.

**Comment by OuyangJunyuan** [comment]
many thanks for your rapid reply!
