### ISSUE TITLE
dataset prep

### ISSUE THREAD

**Issue by anran1231** [Vegeta2020/SE-SSD#75]
Hello, thanks for sharing the code. But I am very confused of dataset preparation. Could you please give more details about data organization? 
Best,
Scarlett

**Comment by Vegeta2020** [comment]
Hi, Scarlett. You may attend to the code in det3d/datasets/kitti and det3d/datasets/pipelines for grasping the overall framework of data preparation, there are several preprocesses like loading/augmentation/voxelization/assigntargets, they are simple but involve many code, so it's a matter of time and patience if you want to understand all. But if you want to do some minor modification, then you can revise the specific module directly as they are independent basically.
