### ISSUE TITLE
When I run 'python ./tools/train.py', I encounter the following problems. How should I solve it

### ISSUE THREAD

**Issue by jiangliangliang2020** [Vegeta2020/SE-SSD#78]
![图片](https://user-images.githubusercontent.com/73384996/162659255-e15b92e7-446b-45fe-949f-488639ef8958.png)

**Comment by magnetmoment** [comment]
Python 3.6 is not compatible. You should try python 3.7.
https://blog.csdn.net/weixin_44789039/article/details/120754136

**Comment by Vegeta2020** [comment]
@jiangliangliang2020 It's caused by the copy.deepcopy() funtion, you may try to change the python version as suggested by @magnetmoment, or you may try to change this line to  
```python
model_ema = build_detector(cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
for param in model_ema.parameters():
    param.detach_()
```
as stated in this [issue](https://github.com/Vegeta2020/SE-SSD/issues/14)

**Comment by sixcomicpen** [comment]
hello！
![image](https://user-images.githubusercontent.com/72868548/163780035-15372757-f108-4241-8fe3-9eddcfa68e39.png)

**Comment by sixcomicpen** [comment]
> Python 3.6 不兼容。你应该试试 python 3.7。 https://blog.csdn.net/weixin_44789039/article/details/120754136

I use version 3.7 of Python to display the following
![1650272754(1)](https://user-images.githubusercontent.com/72868548/163785412-9c520c3f-daef-4536-bd84-6de6ca0f9663.png)

**Comment by Vegeta2020** [comment]
@sixcomicpen How about installing spconv 1.0 or 1.1?

**Comment by sixcomicpen** [comment]
> @sixcomicpen How about installing spconv 1.0 or 1.1?
I got more errors with SPCONv 1.0,like this
![1724ed026d980075dd2f1c4873cce40](https://user-images.githubusercontent.com/72868548/164910693-217f2313-1390-450e-ad03-f9163eeb7659.jpg)

**Comment by jiangliangliang2020** [comment]
> > Python 3.6 不兼容。你应该试试 python 3.7。 https://blog.csdn.net/weixin_44789039/article/details/120754136
> 
> I use version 3.7 of Python to display the following ![1650272754(1)](https://user-images.githubusercontent.com/72868548/163785412-9c520c3f-daef-4536-bd84-6de6ca0f9663.png)

spconv的版本跟python的版本要相匹配，你之前是在python3.6下编译的spconv，不能在python3.7下直接使用，应该重新编译

**Comment by sixcomicpen** [comment]
>这是我重新创建一个新的环境后，安装spconv1.0弹出来的错误

**Comment by sixcomicpen** [comment]
> > > Python 3.6 不兼容。你应该试试 python 3.7。 https://blog.csdn.net/weixin_44789039/article/details/120754136
> > 
> > 
> > I use version 3.7 of Python to display the following ![1650272754(1)](https://user-images.githubusercontent.com/72868548/163785412-9c520c3f-daef-4536-bd84-6de6ca0f9663.png)
> 
> spconv的版本跟python的版本要相匹配，你之前是在python3.6下编译的spconv，不能在python3.7下直接使用，应该重新编译

这是我重新创建一个新的环境后，安装spconv1.0弹出来的错误
