### ISSUE TITLE
Problem during training

### ISSUE THREAD

**Issue by badalpardhi12** [Vegeta2020/SE-SSD#79]
I having an error when I run train.py with pretrained CIA-SSD  model. Any help would be greatly appreciated! Also, any tips on using this model on a custom dataset with 16 channel lidar data. 

![image](https://user-images.githubusercontent.com/66946167/162898215-6d0fff7c-0080-4a12-8c5d-8820bb0af602.png)

**Comment by Vegeta2020** [comment]
@badalpardhi12 From above traceback, there is no points selected for concatenation, and you may check if the class_names are set correctly.  Also, it' easy to change the input lidar data from current 4 channels to 16 channels, you may do it in the config file, but you have to check the data preprocessing files in pipeline carefully to avoid any possible inconsistency.
