### ISSUE TITLE
How is the ap result of Ped/Cyclist on Kitti?

### ISSUE THREAD

**Issue by chenzhenbupt** [Vegeta2020/SE-SSD#8]
Hi, I am interested in how is the ap of Ped/Cyclist on Kitti? Could you share that?

**Comment by Vegeta2020** [comment]
Yes, you may find the results in the supplementary materials of the paper, I remember we only changed the pre-defined anchor size and the number of gt-aug ground truths,  with fast experiments on the two categories.
