### ISSUE TITLE
When I was training, I made the following mistakes

### ISSUE THREAD

**Issue by sixcomicpen** [Vegeta2020/SE-SSD#80]
![1650245124(1)](https://user-images.githubusercontent.com/72868548/163740460-f712e76a-39f4-443a-bb15-f72e5d427d8f.png)
Has anyone solved the problem

**Comment by bhaskar-anand-iith** [comment]
Have you installed det3D separately?

**Comment by sixcomicpen** [comment]
> 您是否单独安装了 det3D？

yes，I have solve this problem,thanks
