### ISSUE TITLE
When I run 'python ./tools/test.py', I encounter the following problems. 

### ISSUE THREAD

**Issue by lwplw** [Vegeta2020/SE-SSD#81]
![image](https://user-images.githubusercontent.com/13364100/163912384-71a69bb7-d8ce-4c5b-9668-e213c26b3b62.png)

I searched for it, this seems to be a numpy version of the problem, and I have tried to reduce the numpy version from 1.21.6 to 1.20.0 is still not resolved, continue to reduce the version will cause other dependent libraries version conflicts, please ask the author of the version of the relevant library, I refer to it, thanks!

**Comment by lwplw** [comment]
Supplement: I run train.py is working properly.

**Comment by lwplw** [comment]
I also found that maybe it was a problem with the [coco API](https://flyfish.blog.csdn.net/article/details/104513632?spm=1001.2101.3001.6650.10&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7Edefault-10.no_search_link&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7Edefault-10.no_search_link), and tried to upgrade to the latest version of pycocotools 2.0.4 as suggested, but still could not solve it.

**Comment by lwplw** [comment]
I solved!
I modified the code in the /SE-SSD/det3d/datasets/kitti/eval .py:
```
for i in range(overlap_ranges.shape[1]):
        for j in range(overlap_ranges.shape[2]):
            # min_overlaps[:, i, j] = np.linspace(*overlap_ranges[:, i, j])
            a, b, c = overlap_ranges[:, i, j]  # extracting the three numbers
            min_overlaps[:, i, j] = np.linspace(a, b, int(c)) # casting to integer
```

**Comment by bhaskar-anand-iith** [comment]
Thank you, I too faced this issue and could solve it using your suggestion..
