### ISSUE TITLE
Error in loading checkpoint while training

### ISSUE THREAD

**Issue by bhaskar-anand-iith** [Vegeta2020/SE-SSD#82]
When I am trying to train the model by

python tools/train.py

I am getting following error

OSError: /mnt/proj50/zhengwu/saved_model/KITTI/proj52/megvii/second/pre_trained_model_2/epoch_60.pth is not a checkpoint file

Which is obvious as I am not giving path to the pretrained model epoch_60.pth. But I want to know why do we need a pretrained model if we want to train from scratch? If it is required, from where do we get epoch_60.pth?

**Comment by Vegeta2020** [comment]
@bhaskar-anand-iith You may download the pre-trained CIA-SSD (see the link in its repository) as this checkpoint, and you also need to revise the checkpoint path in the config file.

**Comment by bhaskar-anand-iith** [comment]
Ok, thank you..

**Comment by lacie-life** [comment]
I downloaded the .pth file from [this](https://github.com/Vegeta2020/CIA-SSD) but met the new error:

"raise IOError("{} is not a checkpoint file".format(filename))
OSError: ~/Dataset/Kitti/saved_model/cia-ssd-model.pth is not a checkpoint file"

Can you help me?

Thanks!
