### ISSUE TITLE
Density or reflectivity?

### ISSUE THREAD

**Issue by liangkangzheng** [Vegeta2020/SE-SSD#85]
Hi Wu Zheng,
I've recently read SE-SSD both paper and code and have found inconsitency in data preprocessing. In paper you mentioned that (x, y, z, density) were the basic features. However I couldn't find the code related to density but only a simple comment that indicates that the 4th feature may be reflectivity. Could you help me out to clarify which feature should we use? And how we get the density of the voxel ?

**Comment by Vegeta2020** [comment]
Hi @liangkangzheng "density" should be a typo and we actually mean intensity, i.e., the reflectivity of laser rays. Thank for yoir reminding.
