### ISSUE TITLE
a question about 'ifp import ifp_sample'

### ISSUE THREAD

**Issue by qinhao1994** [Vegeta2020/SE-SSD#9]
First of all, thank you for your paper!
I tried to use your code, but encountered the following problem
    from ifp import ifp_sample
ModuleNotFoundError: No module named 'ifp'

I can't find anything about 'ifp',Can you help me solve this problem?

**Comment by Vegeta2020** [comment]
Thanks for you feedback. It's an issue about ifp, you may use `git clone https://github.com/jackd/ifp-sample.git;
 pip install -e ifp-sample` to install this module. I also updated README to avoid such a problem.

**Comment by qinhao1994** [comment]
Thank you for your reply！I have solved this problem.
But I ran into a new problem when I tried to run train:
               model_ema = copy.deepcopy(model) 
              TypeError: can't pickle _thread.RLock objects
i have set workers_per_gpu to 0
Looking forward to your reply again

**Comment by lj548502587** [comment]
I also encountered this problem. I created a model_ema repeatedly in train.py to replace its original deepcopy method. After the replacement, the model can be trained normally.

**Comment by Vegeta2020** [comment]
@qinhao1994  I'm not sure the reason for this bug, as it could be run on my machine. And I googled it, the results show it might be solved by correcting parameter setting, perhaps you may try it first. @lijin2021 I tried to avoid repeat copy to keep higher efficiency.
