### ISSUE TITLE
question about ssl training

### ISSUE THREAD

**Issue by JayYangSS** [Vegeta2020/SE-SSD#91]
I found in `trainer_sessd.py`, line334-339, you comment the unlabeled data, Have you try to add the unlabeled data to your training process to finish the semi-supervised training? How's the effect of SSL？

**Comment by Vegeta2020** [comment]
@JayYangSS I tried it but the results were not better....I guess it needs more work to attain further improvement.

**Comment by JayYangSS** [comment]
I try the SSL training, it seems that the unlabel data does not contribute the performance gain. I think pseudo filter need to be designed for a further improvement
